spring:
  application:
    name: authentication-server
  datasource:
    url: jdbc:postgresql://localhost:5432/opr_mgmt
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver  
  jpa:
   properties:
     hibernate:
        jdbc:
          lob:
            non_contextual_creation : true  
   hibernate:
      ddl-auto: update    
   database-platform: org.hibernate.dialect.PostgreSQL9Dialect 
   show-sql: true




server:
  port: 8999  


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
